spring:
  application:
    name: ad-batch
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    meta:
      jdbc-url: jdbc:mysql://localhost:3306/batch
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
    app:
      jdbc-url: jdbc:mysql://localhost:3306/flux
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org.springframework.batch: DEBUG